spring.application.name=PrathibaLanka

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/travel_agency
spring.datasource.username=travel_admin
spring.datasource.password=secret
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.generate-ddl=true

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.org.hibernate.tool.schema=DEBUG
logging.level.org.springframework.orm.jpa=DEBUG

# Email (use a test SMTP like Mailtrap for development)
#spring.mail.host=smtp.mailtrap.io
#spring.mail.port=2525
#spring.mail.username=your_mailtrap_username
#spring.mail.password=your_mailtrap_password
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true