-- The schema as it stood when Flyway was introduced.
--
-- Generated from the live database with:
--   pg_dump -U travel_admin -d travel_agency --schema-only --no-owner --no-privileges --no-comments
-- then stripped of psql session settings and the \restrict meta-command, which is psql syntax and not
-- SQL (Flyway executes migrations through JDBC).
--
-- Two kinds of database run this file, which is why the project sets baseline-on-migrate=true and
-- baseline-version=1:
--
--   * a database that already has these tables (local development, or the day Flyway was added) has
--     no history table, so Flyway records V1 as applied without running it - the tables are already
--     there and their shape is this file;
--   * an empty database (a fresh deployment) runs V1 and gets exactly this schema.
--
-- Either way both end up at version 1 with the same schema, and spring.jpa.hibernate.ddl-auto=validate
-- then proves the entities still match it. Every later change is a new V2__, V3__ file - never an edit
-- to this one, because it has already run in production.







-- Name: admin; Type: TABLE; Schema: public; Owner: -

CREATE TABLE public.admin (
    admin_id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    email character varying(150) NOT NULL,
    full_name character varying(100) NOT NULL,
    password_hash character varying(255) NOT NULL,
    role character varying(50),
    CONSTRAINT admin_role_check CHECK (((role)::text = ANY ((ARRAY['ADMIN'::character varying, 'CUSTOMER'::character varying])::text[])))
);


-- Name: admin_admin_id_seq; Type: SEQUENCE; Schema: public; Owner: -

ALTER TABLE public.admin ALTER COLUMN admin_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.admin_admin_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


-- Name: booking_request; Type: TABLE; Schema: public; Owner: -

CREATE TABLE public.booking_request (
    booking_id bigint NOT NULL,
    confirmed_date date,
    confirmed_price numeric(10,2),
    created_at timestamp(6) without time zone NOT NULL,
    num_travelers integer NOT NULL,
    pin_code character varying(10) NOT NULL,
    preferred_travel_date date NOT NULL,
    special_requests text,
    status character varying(20),
    updated_at timestamp(6) without time zone NOT NULL,
    confirmed_by bigint,
    customer_id bigint NOT NULL,
    package_id bigint NOT NULL,
    version bigint DEFAULT 0 NOT NULL,
    CONSTRAINT booking_request_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'CONFIRMED'::character varying, 'REJECTED'::character varying])::text[])))
);


-- Name: booking_request_booking_id_seq; Type: SEQUENCE; Schema: public; Owner: -

ALTER TABLE public.booking_request ALTER COLUMN booking_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.booking_request_booking_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


-- Name: contact_query; Type: TABLE; Schema: public; Owner: -

CREATE TABLE public.contact_query (
    query_id bigint NOT NULL,
    admin_response text,
    auto_response_sent boolean,
    email character varying(150) NOT NULL,
    message text NOT NULL,
    name character varying(100) NOT NULL,
    phone character varying(20),
    responded_at timestamp(6) without time zone,
    status character varying(20),
    subject character varying(200) NOT NULL,
    submitted_at timestamp(6) without time zone NOT NULL,
    customer_id bigint,
    responded_by bigint,
    CONSTRAINT contact_query_status_check CHECK (((status)::text = ANY ((ARRAY['NEW'::character varying, 'RESPONDED'::character varying])::text[])))
);


-- Name: contact_query_query_id_seq; Type: SEQUENCE; Schema: public; Owner: -

ALTER TABLE public.contact_query ALTER COLUMN query_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.contact_query_query_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


-- Name: customer; Type: TABLE; Schema: public; Owner: -

CREATE TABLE public.customer (
    customer_id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    email character varying(150) NOT NULL,
    full_name character varying(100) NOT NULL,
    password_hash character varying(255),
    phone character varying(20)
);


-- Name: customer_customer_id_seq; Type: SEQUENCE; Schema: public; Owner: -

ALTER TABLE public.customer ALTER COLUMN customer_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.customer_customer_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


-- Name: email_log; Type: TABLE; Schema: public; Owner: -

CREATE TABLE public.email_log (
    log_id bigint NOT NULL,
    body text NOT NULL,
    email_type character varying(30),
    recipient_email character varying(150) NOT NULL,
    sent_at timestamp(6) without time zone NOT NULL,
    subject character varying(200) NOT NULL,
    booking_id bigint,
    sent boolean NOT NULL,
    failure_reason character varying(255),
    CONSTRAINT email_log_email_type_check CHECK (((email_type)::text = ANY ((ARRAY['AUTO_RESPONSE'::character varying, 'PENDING_NOTIFICATION'::character varying, 'CONFIRMATION'::character varying])::text[])))
);


-- Name: email_log_log_id_seq; Type: SEQUENCE; Schema: public; Owner: -

ALTER TABLE public.email_log ALTER COLUMN log_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.email_log_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


-- Name: gallery_image; Type: TABLE; Schema: public; Owner: -

CREATE TABLE public.gallery_image (
    image_id bigint NOT NULL,
    caption character varying(255),
    image_url character varying(255) NOT NULL,
    uploaded_at timestamp(6) without time zone NOT NULL,
    package_id bigint,
    uploaded_by bigint,
    media_type character varying(20),
    CONSTRAINT gallery_image_media_type_check CHECK (((media_type)::text = ANY ((ARRAY['IMAGE'::character varying, 'VIDEO'::character varying])::text[])))
);


-- Name: gallery_image_image_id_seq; Type: SEQUENCE; Schema: public; Owner: -

ALTER TABLE public.gallery_image ALTER COLUMN image_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.gallery_image_image_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


-- Name: journal_post; Type: TABLE; Schema: public; Owner: -

CREATE TABLE public.journal_post (
    journal_id bigint NOT NULL,
    content text NOT NULL,
    cover_image_url character varying(255),
    created_at timestamp(6) without time zone NOT NULL,
    description text,
    published_at timestamp(6) without time zone,
    status character varying(20),
    title character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL
);


-- Name: journal_post_journal_id_seq; Type: SEQUENCE; Schema: public; Owner: -

ALTER TABLE public.journal_post ALTER COLUMN journal_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.journal_post_journal_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


-- Name: media_asset; Type: TABLE; Schema: public; Owner: -

CREATE TABLE public.media_asset (
    media_id bigint NOT NULL,
    content_type character varying(100) NOT NULL,
    media_type character varying(20) NOT NULL,
    original_name character varying(255) NOT NULL,
    size_bytes bigint NOT NULL,
    stored_name character varying(120) NOT NULL,
    title character varying(255),
    uploaded_at timestamp(6) without time zone NOT NULL,
    url character varying(255) NOT NULL,
    uploaded_by bigint,
    CONSTRAINT media_asset_media_type_check CHECK (((media_type)::text = ANY ((ARRAY['IMAGE'::character varying, 'VIDEO'::character varying])::text[])))
);


-- Name: media_asset_media_id_seq; Type: SEQUENCE; Schema: public; Owner: -

ALTER TABLE public.media_asset ALTER COLUMN media_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.media_asset_media_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


-- Name: page_content; Type: TABLE; Schema: public; Owner: -

CREATE TABLE public.page_content (
    content_id bigint NOT NULL,
    payload text NOT NULL,
    section character varying(40) NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    updated_by bigint,
    CONSTRAINT page_content_section_check CHECK (((section)::text = ANY ((ARRAY['ABOUT'::character varying, 'CONTACT'::character varying])::text[])))
);


-- Name: page_content_content_id_seq; Type: SEQUENCE; Schema: public; Owner: -

ALTER TABLE public.page_content ALTER COLUMN content_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.page_content_content_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


-- Name: review; Type: TABLE; Schema: public; Owner: -

CREATE TABLE public.review (
    review_id bigint NOT NULL,
    comment text,
    created_at timestamp(6) without time zone NOT NULL,
    rating integer NOT NULL,
    customer_id bigint NOT NULL,
    package_id bigint
);


-- Name: review_review_id_seq; Type: SEQUENCE; Schema: public; Owner: -

ALTER TABLE public.review ALTER COLUMN review_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.review_review_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


-- Name: travel_package; Type: TABLE; Schema: public; Owner: -

CREATE TABLE public.travel_package (
    package_id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    created_by bigint,
    description text,
    destination character varying(150),
    duration_days integer,
    itinerary text,
    max_capacity integer,
    price numeric(10,2),
    status character varying(255),
    title character varying(150) NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    image_url character varying(255),
    long_description text,
    CONSTRAINT travel_package_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'INACTIVE'::character varying])::text[])))
);


-- Name: travel_package_package_id_seq; Type: SEQUENCE; Schema: public; Owner: -

ALTER TABLE public.travel_package ALTER COLUMN package_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.travel_package_package_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


-- Name: admin admin_pkey; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.admin
    ADD CONSTRAINT admin_pkey PRIMARY KEY (admin_id);


-- Name: booking_request booking_request_pkey; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.booking_request
    ADD CONSTRAINT booking_request_pkey PRIMARY KEY (booking_id);


-- Name: contact_query contact_query_pkey; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.contact_query
    ADD CONSTRAINT contact_query_pkey PRIMARY KEY (query_id);


-- Name: customer customer_pkey; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.customer
    ADD CONSTRAINT customer_pkey PRIMARY KEY (customer_id);


-- Name: email_log email_log_pkey; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.email_log
    ADD CONSTRAINT email_log_pkey PRIMARY KEY (log_id);


-- Name: gallery_image gallery_image_pkey; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.gallery_image
    ADD CONSTRAINT gallery_image_pkey PRIMARY KEY (image_id);


-- Name: journal_post journal_post_pkey; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.journal_post
    ADD CONSTRAINT journal_post_pkey PRIMARY KEY (journal_id);


-- Name: media_asset media_asset_pkey; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.media_asset
    ADD CONSTRAINT media_asset_pkey PRIMARY KEY (media_id);


-- Name: page_content page_content_pkey; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.page_content
    ADD CONSTRAINT page_content_pkey PRIMARY KEY (content_id);


-- Name: review review_pkey; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.review
    ADD CONSTRAINT review_pkey PRIMARY KEY (review_id);


-- Name: travel_package travel_package_pkey; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.travel_package
    ADD CONSTRAINT travel_package_pkey PRIMARY KEY (package_id);


-- Name: admin ukc0r9atamxvbhjjvy5j8da1kam; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.admin
    ADD CONSTRAINT ukc0r9atamxvbhjjvy5j8da1kam UNIQUE (email);


-- Name: customer ukdwk6cx0afu8bs9o4t536v1j5v; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.customer
    ADD CONSTRAINT ukdwk6cx0afu8bs9o4t536v1j5v UNIQUE (email);


-- Name: booking_request ukfg23cc85pon2kwi8ltfkklrdp; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.booking_request
    ADD CONSTRAINT ukfg23cc85pon2kwi8ltfkklrdp UNIQUE (pin_code);


-- Name: media_asset ukg7fqw7h4r8r8d497c1b48k5al; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.media_asset
    ADD CONSTRAINT ukg7fqw7h4r8r8d497c1b48k5al UNIQUE (stored_name);


-- Name: page_content ukgwldyhplm926vhuic91c5jq4w; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.page_content
    ADD CONSTRAINT ukgwldyhplm926vhuic91c5jq4w UNIQUE (section);


-- Name: gallery_image fk20okfwfb7yjyh1p4y7fe6983p; Type: FK CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.gallery_image
    ADD CONSTRAINT fk20okfwfb7yjyh1p4y7fe6983p FOREIGN KEY (uploaded_by) REFERENCES public.admin(admin_id);


-- Name: gallery_image fk3ulnecj5kqoh6v6kean6jicox; Type: FK CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.gallery_image
    ADD CONSTRAINT fk3ulnecj5kqoh6v6kean6jicox FOREIGN KEY (package_id) REFERENCES public.travel_package(package_id);


-- Name: review fk3v423gk4lrmnkv7k3v3uaiqgm; Type: FK CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.review
    ADD CONSTRAINT fk3v423gk4lrmnkv7k3v3uaiqgm FOREIGN KEY (package_id) REFERENCES public.travel_package(package_id);


-- Name: booking_request fk61hgg9gsl5l5vueayjgldul4g; Type: FK CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.booking_request
    ADD CONSTRAINT fk61hgg9gsl5l5vueayjgldul4g FOREIGN KEY (customer_id) REFERENCES public.customer(customer_id);


-- Name: page_content fk6ja16y5o2gxa37ki9n4myqtlr; Type: FK CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.page_content
    ADD CONSTRAINT fk6ja16y5o2gxa37ki9n4myqtlr FOREIGN KEY (updated_by) REFERENCES public.admin(admin_id);


-- Name: contact_query fkb82ffb1441noc58mxcbjk4sn6; Type: FK CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.contact_query
    ADD CONSTRAINT fkb82ffb1441noc58mxcbjk4sn6 FOREIGN KEY (customer_id) REFERENCES public.customer(customer_id);


-- Name: review fkgce54o0p6uugoc2tev4awewly; Type: FK CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.review
    ADD CONSTRAINT fkgce54o0p6uugoc2tev4awewly FOREIGN KEY (customer_id) REFERENCES public.customer(customer_id);


-- Name: booking_request fkm8ukhe8h3rxmxyppmqg97j1w4; Type: FK CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.booking_request
    ADD CONSTRAINT fkm8ukhe8h3rxmxyppmqg97j1w4 FOREIGN KEY (confirmed_by) REFERENCES public.admin(admin_id);


-- Name: contact_query fkowl10tvcewmcq6wcirvddgn9f; Type: FK CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.contact_query
    ADD CONSTRAINT fkowl10tvcewmcq6wcirvddgn9f FOREIGN KEY (responded_by) REFERENCES public.admin(admin_id);


-- Name: media_asset fkqgv2b2mrrejdayltwja4ult0o; Type: FK CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.media_asset
    ADD CONSTRAINT fkqgv2b2mrrejdayltwja4ult0o FOREIGN KEY (uploaded_by) REFERENCES public.admin(admin_id);


-- Name: booking_request fkrfixy9uh0smvhm0ekxfm6m0ma; Type: FK CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.booking_request
    ADD CONSTRAINT fkrfixy9uh0smvhm0ekxfm6m0ma FOREIGN KEY (package_id) REFERENCES public.travel_package(package_id);


-- Name: email_log fkrkv5d97apbhwglwhfxqia00u9; Type: FK CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.email_log
    ADD CONSTRAINT fkrkv5d97apbhwglwhfxqia00u9 FOREIGN KEY (booking_id) REFERENCES public.booking_request(booking_id);




