-- The enquiry conversation: one thread per enquiry, a door for the customer, and the two mail types
-- that keep both ends of it informed.
--
-- The model this serves, in one paragraph. There are two kinds of enquiry - a general one (the
-- contact form) and one about a package (the Request button, which becomes a booking request with a
-- PIN and a status). Only the package kind is a state machine: pending, confirmed, cancelled, each
-- announced automatically. Everything else is a conversation, and the agency has that conversation in
-- its own inbox, not in this application. So the application's job is to carry the messages that
-- matter, keep the record, and route replies to a mailbox that a person actually reads.
--
-- Three things were missing for that:
--
--   1. The admin console could store a reply and told everybody it was "saved against the enquiry" -
--      but nothing was ever sent. The customer's only answer was silence. QUERY_RESPONSE is the mail
--      that fixes it, and reply_sent records whether it actually left.
--   2. A general enquiry had no door for the customer: the acknowledgement quoted a reference number
--      that no page in the application accepted. access_token is an unguessable secret (the reference
--      stays the readable, sequential id) that opens their own page.
--   3. Nothing recorded the conversation. query_message does, and query_message.emailed separates "we
--      sent this" from "a person sent this from their own inbox" - which is the normal case here and
--      has to be visible rather than looking like a failure.

-- ---------------------------------------------------------------- the customer's door

-- A 128-bit random secret, not the query id: /api/enquiries/{token} is public, and a sequential id
-- would let anybody read anybody's enquiry by counting upwards.
ALTER TABLE public.contact_query ADD COLUMN access_token character varying(64);

-- Backfill before the NOT NULL, so an existing database upgrades in place. gen_random_uuid() is core
-- in PostgreSQL 13 and later, so no pgcrypto extension is needed for a one-off generated value.
UPDATE public.contact_query
   SET access_token = replace(gen_random_uuid()::text, '-', '')
 WHERE access_token IS NULL;

ALTER TABLE public.contact_query ALTER COLUMN access_token SET NOT NULL;
ALTER TABLE public.contact_query ADD CONSTRAINT contact_query_access_token_key UNIQUE (access_token);

-- ---------------------------------------------------------------- what happened to the reply

-- Did the reply we composed actually reach the customer? Mirrors auto_response_sent, which already
-- works this way for the acknowledgement: the flag is written by the mail worker after the response,
-- from what the transport said, not from what the request hoped.
ALTER TABLE public.contact_query ADD COLUMN reply_sent boolean DEFAULT false NOT NULL;

-- The agency answered from its own inbox instead. This is a real outcome rather than a failure - it
-- is how the discussions actually happen - but it is not the same as a reply that failed to send, and
-- the console has to be able to say which one it is looking at.
ALTER TABLE public.contact_query ADD COLUMN answered_outside boolean DEFAULT false NOT NULL;

-- ---------------------------------------------------------------- the thread

CREATE TABLE public.query_message (
    message_id bigint NOT NULL,
    query_id bigint NOT NULL,
    -- CUSTOMER is the person who wrote in, AGENCY is anybody answering on behalf of Prathibha Lanka.
    direction character varying(16) NOT NULL,
    -- Nullable on purpose: "I answered from my phone" is worth recording even when nobody kept a copy
    -- of what was sent. The console shows that as no copy kept rather than as an empty message.
    body text,
    author_name character varying(100),
    -- True when this application sent the message. False means a person sent it themselves, which is
    -- the normal case for AGENCY messages.
    emailed boolean DEFAULT false NOT NULL,
    author_admin_id bigint,
    created_at timestamp(6) without time zone NOT NULL,
    CONSTRAINT query_message_direction_check
        CHECK (((direction)::text = ANY ((ARRAY['CUSTOMER'::character varying, 'AGENCY'::character varying])::text[])))
);

ALTER TABLE public.query_message ALTER COLUMN message_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.query_message_message_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE public.query_message ADD CONSTRAINT query_message_pkey PRIMARY KEY (message_id);

-- Deleting an enquiry takes its thread with it: a message with no enquiry is unreachable.
ALTER TABLE public.query_message ADD CONSTRAINT fk_query_message_query
    FOREIGN KEY (query_id) REFERENCES public.contact_query(query_id) ON DELETE CASCADE;

-- Who on the staff side wrote or recorded it. Null for customer messages.
ALTER TABLE public.query_message ADD CONSTRAINT fk_query_message_admin
    FOREIGN KEY (author_admin_id) REFERENCES public.admin(admin_id);

-- The thread is always read for one enquiry, in order.
CREATE INDEX idx_query_message_query ON public.query_message (query_id, created_at);

-- Replies already stored in contact_query.admin_response never went out by mail - that is the whole
-- reason this migration exists - so they are carried into the thread as answered outside the system
-- rather than as messages that were sent.
INSERT INTO public.query_message (query_id, direction, body, author_name, emailed, author_admin_id, created_at)
SELECT q.query_id,
       'AGENCY',
       q.admin_response,
       a.full_name,
       false,
       q.responded_by,
       COALESCE(q.responded_at, q.submitted_at)
  FROM public.contact_query q
  LEFT JOIN public.admin a ON a.admin_id = q.responded_by
 WHERE q.admin_response IS NOT NULL
   AND btrim(q.admin_response) <> '';

-- One reply per enquiry is now the thread's business, and two places to write a reply is one place too
-- many. The API keeps returning the latest agency reply for the console's one-line summary, computed
-- from the thread.
ALTER TABLE public.contact_query DROP COLUMN admin_response;

-- ---------------------------------------------------------------- the two new mails

-- QUERY_RESPONSE - the agency's reply, sent to the customer.
-- QUERY_MESSAGE  - "the customer wrote again", sent to the agency inbox that answers.
--
-- The constraint matters more than it looks, exactly as it did for CANCELLATION in V3: sendAndLog
-- sends the message *before* it writes the row, so a type the constraint refuses means the mail went
-- out and the audit trail silently did not record it. Dropped by name because a database baselined
-- from V1 carries the same auto-generated name.
ALTER TABLE public.email_log DROP CONSTRAINT IF EXISTS email_log_email_type_check;

ALTER TABLE public.email_log ADD CONSTRAINT email_log_email_type_check
    CHECK (email_type::text = ANY (ARRAY[
        'AUTO_RESPONSE'::character varying,
        'PENDING_NOTIFICATION'::character varying,
        'CONFIRMATION'::character varying,
        'CANCELLATION'::character varying,
        'QUERY_RESPONSE'::character varying,
        'QUERY_MESSAGE'::character varying
    ]::text[]));
