-- Changing an admin password from inside the application, instead of from Railway's variables.
--
-- Until now the only way to change this password was BOOTSTRAP_ADMIN_PASSWORD plus
-- BOOTSTRAP_ADMIN_RESET_PASSWORD and a redeploy: the agency could not do it themselves, and the
-- password sat in a hosting dashboard where it was readable by anyone with project access. Two
-- additions fix that.
--
--   admin.password_changed_at   Tokens issued before a password change are refused from then on.
--                               Without it, changing a password leaves every session that was
--                               already open working for the rest of the day - which is the wrong
--                               answer in exactly the case that matters, when the reason for
--                               changing it is that somebody else may know it.
--
--   password_reset_code         The one-time code emailed to an admin who has forgotten theirs.
--                               Only the BCrypt hash is stored, so a database dump does not hand
--                               anybody a working code, and a code cannot be recovered by reading
--                               the table.
--
-- Nullable and without a default on purpose: every admin that already exists has never changed its
-- password, so no token of theirs is refused.

ALTER TABLE public.admin ADD COLUMN password_changed_at timestamp;

CREATE TABLE public.password_reset_code (
    reset_id     bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admin_id     bigint NOT NULL,
    code_hash    varchar(255) NOT NULL,
    expires_at   timestamp NOT NULL,
    requested_at timestamp NOT NULL DEFAULT now(),
    used_at      timestamp,
    attempts     integer NOT NULL DEFAULT 0,
    CONSTRAINT password_reset_code_admin_fk FOREIGN KEY (admin_id)
        REFERENCES public.admin (admin_id) ON DELETE CASCADE
);

-- Every lookup is "the newest unused code for this admin", which is what the index serves.
CREATE INDEX password_reset_code_admin_requested_idx
    ON public.password_reset_code (admin_id, requested_at DESC);

-- The email_log constraint is rewritten for the same reason it was in V3 and V4, and the reason is
-- worth repeating: sendAndLog sends the message *before* it writes the audit row, so a type the
-- check refuses means the mail went out and the record of it silently did not. Dropped by name
-- because a database baselined from V1 carries the same auto-generated constraint name.
ALTER TABLE public.email_log DROP CONSTRAINT IF EXISTS email_log_email_type_check;

ALTER TABLE public.email_log ADD CONSTRAINT email_log_email_type_check
    CHECK (email_type::text = ANY (ARRAY[
        'AUTO_RESPONSE'::character varying,
        'PENDING_NOTIFICATION'::character varying,
        'CONFIRMATION'::character varying,
        'CANCELLATION'::character varying,
        'QUERY_RESPONSE'::character varying,
        'QUERY_MESSAGE'::character varying,
        'PASSWORD_RESET'::character varying
    ]::text[]));
